//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("0.2.0.5")]
[assembly: System.Reflection.AssemblyFileVersion("0.2.0.5")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2016 BoykaTheMad. All rights reserved.")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.2.0.5")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyVersion = "0.2.0.5";
    
    internal const string AssemblyFileVersion = "0.2.0.5";
    
    internal const string AssemblyCopyright = "Copyright © 2016 BoykaTheMad. All rights reserved.";
    
    internal const string AssemblyInformationalVersion = "0.2.0.5";
    
    private ThisAssembly() {
    }
}
